spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 47221d1990da8cd77692
            clientSecret: 9e9de05b58fa370c652a745b237c1a8ab8c7d0b4
          google:
            client-id: 1035737804646-553vih6ufupb3vbubhp7hub6h62hbdlq.apps.googleusercontent.com
            client-secret: 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