spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 47221d1990da8cd77692
            clientSecret: dfd357a3ec578ccfce212af292db33172442e890
          google:
            client-id: 1035737804646-uurad3d2g0i3ue3eb4k9e73q96s03kbb.apps.googleusercontent.com
            client-secret: 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